[workspace]
resolver = "2"
members = ["client", "controller"]

[patch.crates-io]
kube = { git = "https://github.com/clux/kube-rs", branch = "master" }
kube-runtime = { git = "https://github.com/clux/kube-rs", branch = "master" }
