[package]
name = "polixy"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"
publish = false

[dependencies]
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
kube = { version = "0.51.0", default-features = false, features = ["rustls-tls"] }
kube-runtime = { version = "0.51.0", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
