apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    plural: servers
    singular: server
    kind: Server
    shortNames: [srv]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - pods
                - port
              properties:
                pods:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: object
                      properties:
                        key: {type: string}
                        operator:
                          type: string
                          enum: [In, NotIn]
                        values:
                          type: array
                          items: {type: string}
                port:
                  x-kubernetes-int-or-string: true
                proxyProtocol:
                  type: string
                  default: Unknown
                  enum:
                    - Unknown
                    - Http
                    - Grpc
                    - Opaque
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesses.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    plural: accesses
    singular: access
    kind: Access
    shortNames: [axs]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            servers:
              type: object
              properties:
                matchLabels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                matchExpressions:
                  type: object
                  properties:
                    key: {type: string}
                    operator:
                      type: string
                      enum: [In, NotIn]
                    values:
                      type: array
                      items: {type: string}
