apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-bot
      app.kubernetes.io/part-of: emojivoto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-bot
        app.kubernetes.io/part-of: emojivoto
        app.kubernetes.io/version: v11
    spec:
      serviceAccountName: vote-bot
      containers:
        - name: main
          image: docker.l5d.io/buoyantio/emojivoto-web:v11
          command: [emojivoto-vote-bot]
          env:
            - name: WEB_HOST
              value: web:80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 100Mi

