apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: web
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/part-of: emojivoto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/part-of: emojivoto
        app.kubernetes.io/version: v11
    spec:
      serviceAccountName: web
      containers:
        - name: main
          image: docker.l5d.io/buoyantio/emojivoto-web:v11
          env:
            - name: WEB_PORT
              value: "8080"
            - name: EMOJISVC_HOST
              value: emoji:8080
            - name: VOTINGSVC_HOST
              value: voting:8080
            - name: INDEX_BUNDLE
              value: dist/index_bundle.js
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 100Mi
---
apiVersion: polixy.olix0r.net/v1
kind: Server
metadata:
  namespace: emojivoto
  name: web-http
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: web
    app.kubernetes.io/version: v11
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
      app.kubernetes.io/name: web
  port: http
  proxyProtocol: Http
---
apiVersion: polixy.olix0r.net/v1
kind: Authorization
metadata:
  namespace: emojivoto
  name: web-public
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: web
    app.kubernetes.io/version: v11
spec:
  server:
    name: web-http
  # Allow all clients to access the web HTTP port without regard for
  # authentication. If unauthenticated connections are permitted, there is no
  # need to describe authenticated clients.
  unauthenticated:
    networks:
      - 0.0.0.0/0
