apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authorizations.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    kind: Authorization
    plural: authorizations
    singular: authorization
    shortNames: [authz]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              description: >-
                Authorizes clients to communicate with Linkerd-proxied servers.
              type: object
              required: [server]
              oneOf:
                - required: [authenticated]
                - required: [unauthenticated]
              properties:

                server:
                  description: >-
                    Identifies servers in the same namespace for which this
                    authorization applies.

                    Only one of `name` or `selector` may be specified.
                  type: object
                  oneOf:
                    - required: [name]
                    - required: [selector]
                  properties:
                    name:
                      description: References a `Server` instance by name
                      type: string
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                    selector:
                      description: >-
                        A label query over servers on which this authorization applies.
                      type: object
                      oneOf:
                        - required: [matchLabels]
                        - required: [matchExpressions]
                      properties:
                        matchLabels:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            required: [key, operator, value]
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                                enum: [In, NotIn]
                              values:
                                type: array
                                items:
                                  type: string

                authenticated:
                  description: >-
                    Authorizes a clients to connect to a server with Linkerd
                    mTLS identity.
                  type: object
                  oneOf:
                    - required: [identities]
                    - required: [serviceAccounts]
                  properties:

                    identities:
                      description: >-
                        Authorizes authenticated clients with the provided
                        identity strings.

                        The `*` prefix can be used to match all identities in
                        a domain. An identity string of `*` indicates that
                        all authenticated clients are authorized.
                      type: array
                      items:
                        type: string
                        pattern: '^(\*|[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)$'

                    serviceAccountRefs:
                      type: array
                      items:
                        type: object
                        required: [name]
                        properties:
                          namespace:
                            type: string
                            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                          name:
                            type: string
                            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                    serviceAccountSelectors:
                      type: array
                      items:
                        type: object
                        oneOf:
                          - required: [matchLabels]
                          - required: [matchExpressions]
                        properties:
                          matchLabels:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              required: [key, operator, values]
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                  enum: [In, NotIn]
                                values:
                                  type: array
                                  items:
                                    type: string

                          # When unspecified, matches ALL namespaces.
                          namespaceSelector:
                            type: object
                            oneOf:
                              - required: [matchLabels]
                              - required: [matchExpressions]
                            properties:
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required: [key, operator, values]
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum: [In, NotIn]
                                    values:
                                      type: array
                                      items:
                                        type: string

                unauthenticated:
                  description: >-
                    Authorizes unauthenticated clients to connect to a server
                  type: object
                  required: [networks]
                  properties:
                    networks:
                      description: Authorizes traffic from specified CIDR blocks
                      type: array
                      items:
                        type: string
