apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authorizations.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    kind: Authorization
    plural: authorizations
    singular: authorization
    shortNames: [authz]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              properties:
                # References a `Server` instance in the same namespace.
                serverName:
                  type: string
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                # Selects `Server` instances in the same namespace.
                serverSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: [In, NotIn]
                          values:
                            type: array
                            items:
                              type: string
                        required:
                          - key
                          - operator
                          - values
                authorizations:
                  type: array
                  items:
                    type: object
                    properties:
                      unauthenticated:
                        type: object
                        properties:
                          any:
                            type: boolean
                          parentNode:
                            type: boolean
                          network:
                            type: string
                        # oneOf:
                        #   - properties:
                        #       any: {}
                        #   - properties:
                        #       parentNode: {}
                        #   - properties:
                        #       network: {}
                      authenticated:
                        type: object
                        properties:
                          any:
                            type: boolean
                          identity:
                            type: string
                          serviceAccountRef:
                            type: object
                            properties:
                              name:
                                type: string
                                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                              namespace:
                                type: string
                                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                            required:
                              - name
                          serviceAccountSelector:
                            type: object
                            properties:
                              namespace:
                                type: string
                                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum: [In, NotIn]
                                    values:
                                      type: array
                                      items:
                                        type: string
                                  required:
                                    - key
                                    - operator
                                    - values
                        # oneOf:
                        #   - properties:
                        #       any: {}
                        #   - properties:
                        #       identity: {}
                        #   - properties:
                        #       serviceAccountSelector: {}
                        #   - properties:
                        #       serviceAccountRef: {}
              required:
                - authorizations
              # oneOf:
              #   - properties:
              #       serverName: {}
              #   - properties:
              #       serverSelector: {}
