apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authorizations.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    kind: Authorization
    plural: authorizations
    singular: authorization
    shortNames: [authz]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [clients, server]
              properties:
                clients:
                  type: array
                  items:
                    type: object
                    properties:
                      unauthenticated:
                        type: object
                        properties:
                          any:
                            type: boolean
                            enum: [true]
                          network:
                            type: string
                          node:
                            type: boolean
                            enum: [true]
                        oneOf:
                          - required: [any]
                          - required: [node]
                          - required: [network]
                      authenticated:
                        type: object
                        properties:
                          any:
                            type: boolean
                            enum: [true]
                          identity:
                            type: string
                            pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                          serviceAccount:
                            type: object
                            properties:
                              name:
                                type: string
                                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                              namespace:
                                type: string
                                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                              matchLabels:
                                type: object
                                x-kubernetes-preserve-unknown-fields: true
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  required: [key, operator, values]
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                      enum: [In, NotIn]
                                    values:
                                      type: array
                                      items:
                                        type: string
                            oneOf:
                              - required: [name]
                              - required: [matchLabels]
                              - required: [matchExpressions]
                        oneOf:
                          - required: [any]
                          - required: [identity]
                          - required: [serviceAccount]
                    oneOf:
                      - required: [unauthenticated]
                      - required: [authenticated]

                # References `Server` instances in the same namespace.
                server:
                  type: object
                  properties:
                    name:
                      type: string
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required: [key, operator, value]
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: [In, NotIn]
                          values:
                            type: array
                            items:
                              type: string
                  oneOf:
                    - required: [name]
                    - required: [matchLabels]
                    - required: [matchExpressions]
