apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.polixy.olix0r.net
spec:
  group: polixy.olix0r.net
  names:
    kind: Server
    plural: servers
    singular: server
    shortNames: [srv]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required:
                - podSelector
                - port
              properties:
                podSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required: [key, operator, values]
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: [In, NotIn]
                          values:
                            type: array
                            items:
                              type: string
                port:
                  x-kubernetes-int-or-string: true
                proxyProtocol:
                  type: string
                  default: Unknown
                  enum:
                    - Unknown
                    - Http
                    - Grpc
                    - Opaque
