---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emoji
  namespace: emojivoto
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
---
apiVersion: v1
kind: Service
metadata:
  name: emoji
  namespace: emojivoto
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
    app.kubernetes.io/version: v11
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: prom
      port: 8801
      targetPort: 8801
  selector:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
    app.kubernetes.io/version: v11
  name: emoji
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
      app.kubernetes.io/name: emoji
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: emojivoto
        app.kubernetes.io/name: emoji
        app.kubernetes.io/version: v11
    spec:
      serviceAccountName: emoji
      containers:
        - name: main
          image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
          env:
            - name: GRPC_PORT
              value: "8080"
            - name: PROM_PORT
              value: "8801"
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8801
              name: prom
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 100Mi
---
apiVersion: polixy.olix0r.net/v1
kind: Server
metadata:
  namespace: emojivoto
  name: emoji-grpc
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
    app.kubernetes.io/version: v11
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
      app.kubernetes.io/name: emoji
  port: grpc
  proxyProtocol: Grpc
---
apiVersion: polixy.olix0r.net/v1
kind: Authorization
metadata:
  namespace: emojivoto
  name: emoji-grpc
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: emoji
    app.kubernetes.io/version: v11
spec:
  # Allow all authenticated clients to access the (read-only) emoji service.
  server:
    name: emoji-grpc
  authenticated:
    identities: ['*']
