---
apiVersion: v1
kind: Namespace
metadata:
  name: emojivoto
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-log-level: info
---
apiVersion: polixy.olix0r.net/v1alpha1
kind: Server
metadata:
  namespace: emojivoto
  name: prom
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  port: prom
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
  proxyProtocol: Http
---
apiVersion: polixy.olix0r.net/v1alpha1
kind: Authorization
metadata:
  namespace: emojivoto
  name: prom-prometheus
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  server:
    name: prom
  client:
    mtls:
      serviceAccounts:
        - namespace: linkerd-viz
          name: prometheus
