---
apiVersion: polixy.olix0r.net/v1alpha1
kind: Server
metadata:
  namespace: linkerd
  name: linkerd-destination-grpc
spec:
  port: 8086
  proxyProtocol: Grpc
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
      linkerd.io/control-plane-component: destination
---
apiVersion: polixy.olix0r.net/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: linkerd
  name: linkerd-destination-grpc
spec:
  server:
    name: linkerd-destination-grpc
  client:
    mtls:
      identities: ["*"]
