---
apiVersion: polixy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: linkerd
  name: linkerd-admin
  labels:
    viz.linkerd.io/prometheus: allow
spec:
  port: linkerd-admin
  proxyProtocol: HTTP/1
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
---
apiVersion: polixy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: linkerd
  name: admin-http
  labels:
    viz.linkerd.io/prometheus: allow
spec:
  port: admin-http
  proxyProtocol: HTTP/1
  podSelector:
    matchExpressions:
      -  key: linkerd.io/control-plane-component
         operator: NotIn
         values: []
---
apiVersion: polixy.linkerd.io/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: linkerd
  name: admin-prometheus
spec:
  server:
    selector:
      matchLabels:
        viz.linkerd.io/prometheus: allow
  client:
    meshTLS:
      serviceAccounts:
        - namespace: linkerd-viz
          name: prometheus
