---
apiVersion: polixy.olix0r.net/v1alpha1
kind: Server
metadata:
  namespace: linkerd
  name: linkerd-sp-validator-https
spec:
  port: 8443
  proxyProtocol: Tls
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
      linkerd.io/control-plane-component: destination
---
apiVersion: polixy.olix0r.net/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: linkerd
  name: linkerd-sp-validator-https
spec:
  server:
    name: linkerd-sp-validator-https
  client:
    unauthenticated: true
    # TODO limit to pod networks.
