---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.polixy.olix0r.net
  labels:
    polixy.olix0r.net/crd: srv
spec:
  group: polixy.olix0r.net
  names:
    kind: Server
    plural: servers
    singular: server
    shortNames: [srv]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true

      additionalPrinterColumns:
        - jsonPath: .spec.port
          name: podSelector
          type: string
        - jsonPath: .spec.podSelector
          name: port
          type: string

      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required:
                - podSelector
                - port
              properties:

                podSelector:
                  type: object
                  description: >-
                    Selects pods in the same namespace.
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required: [key, operator, values]
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: [In, NotIn]
                          values:
                            type: array
                            items:
                              type: string

                ## XXX Instead of complicating the server with a container
                ## name reference, it's probably better to have an admission
                ## controller that detects ambiguities... I.e., preventing
                ## servers/pods from being created where a port matches more
                ## than one server. It's fine if a single (by-name) server
                ## matches more than one port on a pod.
                #
                # containerName:
                #   description: >-
                #     Indicates the name of the container that `port` refers to.
                #
                #     Kubernetes does not enforce port name uniqueness across
                #     multiple containers in a port. So, when a pod has
                #     containers with overlapping port names, this field can be
                #     used to disambiguate a port.
                #   type: string
                #   pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                port:
                  description: >-
                    A port name or number. Must exist in a pod spec.
                  x-kubernetes-int-or-string: true

                proxyProtocol:
                  description: >-
                    Configures protocol discovery for inbound connections.

                    Supercedes the `config.linkerd.io/opaque-ports` annotation.
                  type: string
                  default: Unknown
                  enum:
                    - unknown
                    - http
                    - grpc
                    - opaque
                    - tls
